services:
  training:
    build:
      context: .
      dockerfile: Dockerfile

    working_dir: /app

    volumes:
      - ./data:/app/data

    environment:
      WANDB_API_KEY: ${WANDB_API_KEY}
      WANDB_PROJECT: ${WANDB_PROJECT}
      WANDB_ENTITY: ${WANDB_ENTITY}
      PYTHONHASHSEED: "42"

    command: python -m src.train


